### ISSUE TITLE
CPU_COUNT for azure

### ISSUE THREAD

**Issue by notestaff** [conda-forge/conda-forge-ci-setup-feedstock#53]
CPU_COUNT here is set to 2; but current conda-smithy on azure seems to set max jobs to 8? https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/templates/azure-pipelines-linux.yml.tmpl#L11 @jakirkham

**Comment by jakirkham** [comment]
Should add this is basically a dup of issue ( https://github.com/conda-forge/conda-forge-ci-setup-feedstock/issues/47 ).

**Comment by mariusvniekerk** [comment]
My view on this one is that we should probably set something like `CPU_COUNT="${CPU_COUNT:-2}"` which would allow the specification of higher numbers of cores per build

**Comment by isuruf** [comment]
@mariusvniekerk, what's a reasonable default for each platform for azure? A maintainer can always override this in their recipe, but it's good to have a reasonable default.

**Comment by mariusvniekerk** [comment]
So on azure. Linux and windows seems to be two and osx 4.

**Comment by isuruf** [comment]
With the conda-smithy development version, the script `recipe/run_conda_forge_build_setup_osx` can use `CI=="azure"` to make it 4 for azure only.

**Comment by ax3l** [comment]
Hijacking this issue, the `CPU_COUNT` on Travis-CI should generally, at least for the free plans, should be 2 instead of unset as well. TravisCI runs mainly on virtual hardware that exposes the full CPU-count (many cores) but actually reserves two: https://docs.travis-ci.com/user/speeding-up-the-build#parallelizing-your-build-on-one-virtual-machine

At least on Travis PPC64le hardware, I see killed compiler processes in my builds due to that `make -j` behaviour: https://github.com/conda-forge/openpmd-api-feedstock/pull/44

**Comment by apmorton** [comment]
bump in 2024 - this is still set to 2 on azure (seen on a recent jaxlib build taking forever).

This also seems to take effect when running `build-locally.py`.

**Comment by hmaarrfk** [comment]
Set the environment variable before the command, or export it.
```
CPU_COUNT=$(nproc) python build-locally.py
```

**Comment by hmaarrfk** [comment]
Given it is 2024, I think we now have the original issue resolvd. If the command above doesn't work for build locally, please re-open the issue.

These CI issues often get stale especially many years later.

**Comment by jakirkham** [comment]
Agreed thanks Mark! 🙏
